### PR TITLE
Unzip source and license files

### LINKED ISSUE #2: A ZIP file?
Is there a reason that you couldnt upload the plain text source code to this repository? That would make it much more accessible without having to download a ZIP file and extract it, which isnt possible on many devices, e.g. mobiles and tablets

### PR DESCRIPTION
**Pull request by Chris-Johnston**
Fixes #2 

This Pull Request unzips the provided source `.zip` file into the root of the project directory.

This improves the ability to view and search through the code, and also copies over the license files. The README has also been merged into a single version of the document.

The ability to download the entire source as a ZIP still remains, GitHub has a button that does it for you and [Git Tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging) can do this also.

### CODE REVIEW

**Comment by tomstorey** [comment]
Its a shame that after all this time it still hasnt been merged. :(

**Comment by skeetor** [comment]
Last update was 2 years ago, so I asume this project is dead. Best you can do is fork it and create your own project.

**Comment by Chris-Johnston** [comment]
> Last update was 2 years ago, so I asume this project is dead.

This project has parts going back to 1986 (CODEGEN.CPP) and the forum's changelog goes back to 2004. Given how old the project is, a 2 year hiatus on new updates seems reasonable.

**Comment by skeetor** [comment]
Maybe. It's a great thing, and I would like to see some improvements, but considering how old the PR is, I wont hold my breath. :)

**Comment by Chris-Johnston** [comment]
This branch is now stale as of dab554f09eb8168d2426a26593d8ff7b67e8515c. I don't think updating this branch is worth the effort to update, so I'm closing this PR.

**Pull request closed without merging**
